export type BlockStyle = Record<string, string | number>;

export interface BlockDef {
  type: string;
  label: string;
  hotkey: string;
  spell: boolean;
  ph: string;
  next: string;
  st: BlockStyle;
  bold?: boolean;
}

export const BLOCK_DEFS: Record<string, BlockDef[]> = {
  film: [
    {
      type: "scene",
      label: "Место и время",
      hotkey: "0",
      spell: false,
      ph: "ИНТ. ЛОКАЦИЯ. ДЕНЬ.",
      next: "cast",
      st: {
        textTransform: "uppercase",
        fontWeight: "bold",
        color: "#f0ece0",
        paddingTop: "32px",
        paddingBottom: "0",
        lineHeight: "1.5",
      },
    },
    {
      type: "cast",
      label: "Участники сцены",
      hotkey: "1",
      spell: false,
      ph: "ГЕРОЙ (возраст), ВТОРОЙ",
      next: "action",
      st: {
        textTransform: "uppercase",
        color: "#aaa",
        paddingTop: "0",
        paddingBottom: "0",
        lineHeight: "1.5",
      },
    },
    {
      type: "action",
      label: "Описание действия",
      hotkey: "2",
      spell: true,
      ph: "Описание действия...",
      next: "action",
      st: { color: "#e0dcd0", paddingTop: "18px", paddingBottom: "0" },
    },
    {
      type: "char",
      label: "Герой",
      hotkey: "3",
      spell: false,
      ph: "ИМЯ ПЕРСОНАЖА",
      next: "dialogue",
      st: {
        textTransform: "uppercase",
        color: "#f0ece0",
        paddingLeft: "211px",
        paddingTop: "18px",
        paddingBottom: "0",
        lineHeight: "1.5",
      },
    },
    {
      type: "dialogue",
      label: "Диалог",
      hotkey: "4",
      spell: true,
      ph: "Слова персонажа...",
      next: "char",
      st: {
        paddingLeft: "96px",
        paddingRight: "144px",
        paddingTop: "0",
        paddingBottom: "0",
      },
    },
    {
      type: "paren",
      label: "Ремарка",
      hotkey: "5",
      spell: true,
      ph: "(действие)",
      next: "dialogue",
      st: {
        paddingLeft: "154px",
        paddingRight: "144px",
        fontStyle: "italic",
        color: "#666",
        paddingTop: "0",
        paddingBottom: "0",
        lineHeight: "1.5",
      },
    },
    {
      type: "spacer",
      label: "Отступ",
      hotkey: "6",
      spell: false,
      ph: "",
      next: "spacer",
      st: { paddingTop: "0", paddingBottom: "0" },
    },
    {
      type: "note",
      label: "Примечание",
      hotkey: "6",
      spell: true,
      ph: "Заметка автора...",
      next: "action",
      st: {
        color: "#4a4a6a",
        fontStyle: "italic",
        borderLeft: "2px solid #2a2a4a",
        paddingLeft: "14px",
        paddingTop: "14px",
        paddingBottom: "4px",
      },
    },
    {
      type: "trans",
      label: "Монтаж",
      hotkey: "7",
      spell: false,
      ph: "CUT TO:",
      next: "scene",
      st: {
        textTransform: "uppercase",
        textAlign: "right",
        paddingTop: "18px",
        paddingBottom: "4px",
        color: "#555",
      },
    },
  ],
  play: [
    {
      type: "act",
      label: "Акт",
      hotkey: "0",
      spell: false,
      ph: "АКТ ПЕРВЫЙ",
      next: "scene",
      st: {
        textTransform: "uppercase",
        fontWeight: "bold",
        color: "#f0ece0",
        textAlign: "center",
        paddingTop: "48px",
        paddingBottom: "8px",
        lineHeight: "1.6",
        fontSize: "15px",
        letterSpacing: "3px",
      },
    },
    {
      type: "scene",
      label: "Сцена",
      hotkey: "1",
      spell: false,
      ph: "",
      next: "cast",
      st: {
        fontWeight: "bold",
        color: "#c8c4e0",
        paddingTop: "24px",
        paddingBottom: "0",
        lineHeight: "1.6",
        fontSize: "14px",
      },
    },
    {
      type: "cast",
      label: "Действующие лица",
      hotkey: "2",
      spell: false,
      ph: "Действующие лица сцены...",
      next: "stage",
      st: {
        color: "#8886aa",
        paddingTop: "0",
        paddingBottom: "0",
        lineHeight: "1.6",
        fontStyle: "italic",
      },
    },
    {
      type: "stage",
      label: "Ремарка",
      hotkey: "3",
      spell: true,
      ph: "Описание места, обстановки...",
      next: "line",
      st: {
        fontStyle: "italic",
        color: "#7a789a",
        paddingTop: "16px",
        paddingBottom: "4px",
        lineHeight: "1.7",
      },
    },
    {
      type: "line",
      label: "Реплика",
      hotkey: "4",
      spell: true,
      ph: "текст реплики...",
      next: "line",
      st: { paddingTop: "4px", paddingBottom: "0", lineHeight: "1.7" },
    },
    {
      type: "spacer",
      label: "Отступ",
      hotkey: "6",
      spell: false,
      ph: "",
      next: "spacer",
      st: { paddingTop: "0", paddingBottom: "0" },
    },
    {
      type: "note",
      label: "Примечание",
      hotkey: "5",
      spell: true,
      ph: "Авторское примечание...",
      next: "stage",
      st: { color: "#4a4a6a", fontStyle: "italic", paddingTop: "14px" },
    },
  ],
  short: [
    {
      type: "scene",
      label: "Блок",
      hotkey: "0",
      spell: false,
      ph: "📍 ЛОКАЦИЯ. ВРЕМЯ.",
      next: "cast",
      st: {
        fontWeight: "bold",
        color: "#f0ece0",
        paddingTop: "28px",
        paddingBottom: "0",
        lineHeight: "1.5",
      },
    },
    {
      type: "cast",
      label: "Участники",
      hotkey: "1",
      spell: false,
      ph: "👤 ПЕРСОНАЖ: ...",
      next: "action",
      st: {
        color: "#777",
        paddingTop: "0",
        paddingBottom: "0",
        lineHeight: "1.5",
        fontSize: "12px",
      },
    },
    {
      type: "action",
      label: "Описание",
      hotkey: "2",
      spell: true,
      ph: "Описание...",
      next: "action",
      st: { paddingTop: "16px" },
    },
    {
      type: "video",
      label: "Видео",
      hotkey: "4",
      spell: false,
      ph: "Видео 1...",
      next: "hook",
      st: {
        color: "#a78bfa",
        fontSize: "13px",
        fontWeight: "bold",
        letterSpacing: "1px",
        paddingTop: "16px",
      },
      bold: true,
    },
    {
      type: "hook",
      label: "Хук",
      hotkey: "5",
      spell: true,
      ph: "[0:00–0:03] Хук...",
      next: "body",
      st: {
        borderLeft: "3px solid #f472b6",
        paddingLeft: "14px",
        color: "#f4d0e0",
        paddingTop: "14px",
      },
    },
    {
      type: "body",
      label: "Основа",
      hotkey: "6",
      spell: true,
      ph: "[0:03–0:45] Основа...",
      next: "cta",
      st: {
        borderLeft: "3px solid #60a5fa",
        paddingLeft: "14px",
        paddingTop: "14px",
      },
    },
    {
      type: "cta",
      label: "CTA",
      hotkey: "7",
      spell: true,
      ph: "[0:45–0:60] CTA...",
      next: "scene",
      st: {
        borderLeft: "3px solid #4ade80",
        paddingLeft: "14px",
        color: "#c8f4d0",
        paddingTop: "14px",
      },
    },
  ],
  media: [
    {
      type: "segment",
      label: "Блок",
      hotkey: "1",
      spell: false,
      ph: "НАЗВАНИЕ  |  0:00",
      next: "anchor",
      st: {
        textTransform: "uppercase",
        fontWeight: "bold",
        color: "#f0ece0",
        paddingTop: "32px",
        paddingBottom: "4px",
        lineHeight: "1.5",
        borderBottom: "1px solid #ffffff22",
        letterSpacing: "2px",
      },
    },
    {
      type: "anchor",
      label: "Подводка",
      hotkey: "2",
      spell: true,
      ph: "Текст ведущего...",
      next: "anchor",
      st: {
        color: "#e0dcd0",
        paddingTop: "12px",
        paddingBottom: "0",
        lineHeight: "1.8",
      },
    },
    {
      type: "sync",
      label: "Синхрон",
      hotkey: "3",
      spell: true,
      ph: "Реплика гостя...",
      next: "anchor",
      st: {
        borderLeft: "3px solid #60a5fa",
        paddingLeft: "14px",
        color: "#c8d8f4",
        fontStyle: "italic",
        paddingTop: "12px",
      },
    },
    {
      type: "vtr",
      label: "ВТР",
      hotkey: "4",
      spell: false,
      ph: "[ВТР] Описание видеопакета...",
      next: "anchor",
      st: {
        borderLeft: "3px solid #f472b6",
        paddingLeft: "14px",
        color: "#f4c8d8",
        paddingTop: "12px",
        fontSize: "12px",
      },
    },
    {
      type: "offscreen",
      label: "Закадр",
      hotkey: "5",
      spell: true,
      ph: "Текст за кадром...",
      next: "anchor",
      st: {
        borderLeft: "3px solid #fbbf24",
        paddingLeft: "14px",
        color: "#f4ecc8",
        paddingTop: "12px",
      },
    },
    {
      type: "lower3",
      label: "Плашка",
      hotkey: "6",
      spell: false,
      ph: "[ПЛАШКА] Имя / Должность",
      next: "anchor",
      st: {
        background: "#ffffff08",
        borderRadius: "4px",
        padding: "6px 12px",
        color: "#aaa",
        fontSize: "12px",
        marginTop: "8px",
        letterSpacing: "1px",
      },
    },
    {
      type: "question",
      label: "Вопрос",
      hotkey: "8",
      spell: true,
      ph: "Вопрос ведущего...",
      next: "note",
      st: {
        fontWeight: "bold",
        color: "#e8e4d8",
        paddingTop: "16px",
        paddingBottom: "0",
        lineHeight: "1.7",
      },
    },
    {
      type: "note",
      label: "Пояснение",
      hotkey: "9",
      spell: true,
      ph: "Контекст, подсказка, уточнение...",
      next: "question",
      st: {
        color: "#6a6a8a",
        fontStyle: "italic",
        fontSize: "12px",
        paddingTop: "4px",
        paddingBottom: "0",
        paddingLeft: "16px",
        borderLeft: "2px solid #3a3a5a",
        lineHeight: "1.6",
      },
    },
    {
      type: "spacer",
      label: "Отступ",
      hotkey: "0",
      spell: false,
      ph: "",
      next: "spacer",
      st: { paddingTop: "0", paddingBottom: "0" },
    },
  ],
  note: [],
};
