import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(frontendRoot, "..");
const htmlPath = path.join(repoRoot, "ИИ начало_w590.html");
const outPath = path.join(frontendRoot, "src/legacy/legacyUiBundle.tsx");

const raw = fs.readFileSync(htmlPath, "utf8");
const lines = raw.split(/\r?\n/);
/** Babel block in source HTML: lines 64–7487 (1-based) */
const body = lines.slice(63, 7487).join("\n");

let out = body.replace(/^const \{ useState, useRef, useEffect, useLayoutEffect, useCallback \} = React;\r?\n/, "");

out = out.replace(/\r?\n\r?\nfunction App\(\)[\s\S]*$/m, "\n");

const header = `// @ts-nocheck
/* Auto-generated by scripts/prepare-legacy.mjs from ../ИИ начало_w590.html */
import React, { useState, useRef, useEffect, useLayoutEffect, useCallback } from "react";

`;

const footer = `
export { Whale, Login, PlayHeaderEditor, EditorScreen, Onboarding };
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, header + out + footer, "utf8");
console.log("Wrote", outPath, "bytes", fs.statSync(outPath).size);
